### ISSUE TITLE
Rack crashing when opening module browser

### ISSUE THREAD

**Issue by catronomix** [catronomix/catro-modulo#11]
In latest commit: https://github.com/catronomix/catro-modulo/commit/d13ba25d361657a35c88bb44010956c6cf1b7abf

I thought I did what this means I should do, but still rack crashes...
I put the if (module){...} check around all the occurences where module->... was used :/

```
1.9
Your ModuleWidgets must gracefully handle a NULL module argument, otherwise Rack will crash when the Module Browser attempts to display your module. createParam() etc. gracefully handle NULL, but if you’ve written custom widgets with a module pointer, make sure you check if (module) ... before accessing the pointer.
```

**Comment by Coirt** [comment]
https://github.com/catronomix/catro-modulo/blob/1.0.0/src/CatroModulo_CM-4.cpp#L106

There is another way to do it which does draw the display. This is the way I have done it on my own displays  

```
//LCD display
		if (module != NULL){
			NumDisplayWidget *display = new NumDisplayWidget();
			display->box.pos = Vec(7.0 , 21.0);
			display->box.size = Vec(61.1 , 20.4);
			display->value = &module->bpm_display;
			addChild(display);
		}
```

My source: https://github.com/Coirt/Bark/blob/master/src/Clamp.cpp#L206

**Comment by JerrySievert** [comment]
you're crashing here:

```
		if (module){
		recball->recball_x = &module->recball_x;
		recball->recball_y = &module->recball_y;
		}else{
			*recball->recball_x = 178.1;
			*recball->recball_y = 89.5;
		}
```

in `CM3_RecBall` you're defining the floats as pointers:

```
	float *recball_x;
	float *recball_y;
```

you're making an invalid assignment, and crashing on null.

specifically:

`*recball->recball_x = 178.1;`
`recball->recball` is at best `NULL`, and at worst some random memory location, so setting it to a value is not something you can do.

**Comment by catronomix** [comment]
Ok I see... I should put the default values directly in the constructor of CM3_RecBall then. Will try it out.

**Comment by catronomix** [comment]
> https://github.com/catronomix/catro-modulo/blob/1.0.0/src/CatroModulo_CM-4.cpp#L106
> 
> There is another way to do it which does draw the display. This is the way I have done it on my own displays
> 
> ```
> //LCD display
> 		if (module != NULL){
> 			NumDisplayWidget *display = new NumDisplayWidget();
> 			display->box.pos = Vec(7.0 , 21.0);
> 			display->box.size = Vec(61.1 , 20.4);
> 			display->value = &module->bpm_display;
> 			addChild(display);
> 		}
> ```
> 
> My source: https://github.com/Coirt/Bark/blob/master/src/Clamp.cpp#L206
@Coirt , doesn't that cause the widget not to be visible in the preview image generated inside the module browser?

**Comment by JerrySievert** [comment]
@catronix gimme a minute and I'll have a PR for you to fix at least this one, should give you a pattern to use.

**Comment by JerrySievert** [comment]
I opened a PR for the first fix, which should act as a pattern - you'll see an additional change that I made, but you'll want to apply the same `if (module)` check when you use the component, like you did for the other component.  this fixes the issue, but you need to make the change in all places you use these components.

from there, they should show up in the module browser.

**Comment by Coirt** [comment]
> > @Coirt , doesn't that cause the widget not to be visible in the preview image generated inside the module browser?

It does yes. What I also do is placehold a replica of the display in the panel.svg this will show in the browser when the module loads the widget is drawn on top of it. 

https://github.com/Coirt/Bark/blob/master/res/BarkClamp.svg

**Comment by catronomix** [comment]
Cool thx, I understand what's happening there I think. Will apply it to everything and test it out :)

**Comment by JerrySievert** [comment]
it will help you to get a debugger up and running (check out @almosteric's suggestion on the other thread on where to look), it was easy for me to figure out where it was crashing in a debugger, but I'm on macOS, and was running `lldb`.

**Comment by catronomix** [comment]
It's working, thanks so much!
![image](https://user-images.githubusercontent.com/42138122/59950746-1b352e80-9477-11e9-9d07-d7bb68bdf877.png)

**Comment by catronomix** [comment]
@JerrySievert 's solution worked a charm! I think I can even revert to limiting the checks on accessing the module pointer so the widgets can still draw, if not, I'll use the mimicking graphics inside the panel background trick :) In any case it's a success :D

**Comment by JerrySievert** [comment]
awesome! happy to help.

just shout if you need anything else.
