### ISSUE TITLE
Fix for compilation warnings - CatroModulo.hpp [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [catronomix/catro-modulo#18]
`src/CatroModulo.hpp: In constructor 'CM_Slider_big_red::CM_Slider_big_red()':
src/CatroModulo.hpp:243:176: warning: 'void rack::app::SvgSlider::setSVGs(std::shared_ptr<rack::Svg>, std::shared_ptr<rack::Svg>)' is deprecated [-Wdeprecated-declarations]
  243 |   setSVGs(APP->window->loadSvg(asset::plugin(pluginInstance, "res/CM-slider_big_red_bg.svg")), APP->window->loadSvg(asset::plugin(pluginInstance, "res/CM-slider_big_red.svg")));`

Line [243](https://github.com/catronomix/catro-modulo/blob/master/src/CatroModulo.hpp#L243) needs to be changed to:
setBackgroundSvg(APP->window->loadSvg(asset::plugin(pluginInstance, "res/CM-slider_big_red_bg.svg")));
setHandleSvg(APP->window->loadSvg(asset::plugin(pluginInstance, "res/CM-slider_big_red.svg")));

Also:

`In file included from src/CatroModulo_CM-8.cpp:1:
src/CatroModulo.hpp: In member function 'float CM_SelSeq::sequence(int)':
src/CatroModulo.hpp:388:11: warning: statement has no effect [-Wunused-value]
  388 |    dostep == true;`

Line [388](https://github.com/catronomix/catro-modulo/blob/master/src/CatroModulo.hpp#L388) should be `dostep = true;`

**Comment by catronomix** [comment]
Oh I see, I forgot to remove the -w flag from my makefile from the v1 conversion so didnt get any warnings. Will fix it thx!

**Comment by catronomix** [comment]
fixed in https://github.com/catronomix/catro-modulo/commit/db3041eec3d59497b660dc751f1601a17bc320cd
