### ISSUE TITLE
syncing to external clock

### ISSUE THREAD

**Issue by paulrobertpine** [catronomix/catro-modulo#20]
Is there a way to sync your clock with an external clock (e.g. coming in from the MIDI-CV module)?

**Comment by catronomix** [comment]
At the moment not, only the cv control for bpm, but I understand the need if you want to integrate the cv system with other clock sources and will most likely add it :)

**Comment by catronomix** [comment]
External clock sync implemented
https://www.youtube.com/watch?v=1ypN057bvO8
